### ISSUE TITLE
support using webpack.config.js instead

### ISSUE THREAD

**Issue by kellyrmilligan** [danez/grunt-webpack#25]
would be nice, and i'll try and take a look, to support either configuration in the gruntfile or if there is a webpack.config.js in the root of the project, to just use that, or to be able to specify a path to the config file. 

an example is the grunt karma task.

**Comment by ansonlouis** [comment]
Maybe I'm missing something, but if I'm doing a grunt-watch and I change the webpack config, I'll have to restart the grunt watch/task from console for the new webpack config to actually be used. Is there a way to get watch to reload the config? Otherwise, an external grunt-webpack option for a config path where the task itself reloads the config on demand would be great.

**Comment by hgoebl** [comment]
It's clear when I read this, but I couldn't imagine doing so when I just was looking for an option. Maybe the README.md could tell about this shortcut?

**Comment by yaitskov** [comment]
If the same grunt file is used to install dependencies for webpack  then plain require is impossible and loading configuration form file is very helpful.
